"""Notebook 14 — MES-M2K DELAYED ENTRY on OWN-SPLICE series (D-022).

NOT the trading algorithm (CLAUDE.md gate 1). Zero orders; the only
subscription exists so `future_chain_provider` can resolve contract symbols.

Identical to `qc_signal_definition_analysis.py` in every respect except the
last step: the same roll schedule, the same `build_continuous`, the same
`splice_audit` acceptance gate with the same A1 adjudication bound. Only the
final call differs — `pair_delayed_entry_report()` — because D-022 moves the
ENTRY BAR of the event study (t+d for d in {1, 2, 5, 15}, on event sets
matched at the largest delay) and adds the leg-level cross-correlation
discriminator. Nothing about event detection changes. Keeping the data path
byte-identical is what makes validity gate 1 meaningful: this run's unmatched
d=1 grids must reproduce the banked notebook-02 (Z0) and notebook-06 (Z2)
grids cell for cell, otherwise the pipeline moved and no delay comparison is
valid.

PART (L-019): the summary-statistic channel has never returned more than 57
keys intact in this project — all four nb06 runs silently lost their 12-key
S_RL block — so the ~103-key battery ships as TWO backtests. Both parts
compute the ENTIRE battery identically; PART filters only which half of the
dict is emitted. Run once with PART = 1 (Z0 half), once with PART = 2 (Z2
half + cross-correlation). The shared diagnostics must come back identical
from both parts (validity gate 2b), which is a fifth determinism check on the
D-009 constructor. This driver deliberately does NOT emit the S_RL per-roll
block; the audit gate still runs and S_GATE / S_FLAG_* carry its result.

Output channel: `set_summary_statistic` in `on_end_of_algorithm` — the free
tier caps logs at 10KB/backtest AND 10KB/day. Values are pipe-delimited; see
`scripts/ingest_qc_delayed_entry.py` for the parser and the D-022 gates.

Uploaded alongside as flat QC project files: roll_adjustment.py, calendars.py,
intraday_reversion.py, crosscorr.py, signals.py, pair_minute_report.py
(generated by `python scripts/build_qc_upload.py --driver delay`, which only
rewrites relative imports; crosscorr.py exists as a separate file because
files/update rejects any file above 32,000 characters).
"""

from AlgorithmImports import *
from datetime import date, datetime, time, timedelta

import pandas as pd

from calendars import cme_holidays
from pair_minute_report import fmt, pair_delayed_entry_report
from roll_adjustment import (
    build_continuous, index_roll_schedule, last_business_day_of_month,
    parse_contract, splice_audit, third_friday, treasury_roll_schedule,
)

# Quarterly chains over the research window. Index micros roll 8 days before a
# 3rd-Friday expiry, so the June-2019 contract is still front on 2019-06-01 and
# the chain opens at M19.
CODES_INDEX = ["M19", "U19", "Z19", "H20", "M20", "U20", "Z20", "H21", "M21",
               "U21", "Z21", "H22", "M22", "U22", "Z22", "H23", "M23", "U23",
               "Z23", "H24", "M24", "U24", "Z24", "H25", "M25", "U25", "Z25",
               "H26", "M26"]
CODES_TREASURY = CODES_INDEX[1:]

TREASURIES = ("ZT", "ZF", "ZN", "ZB")

# D-022 fixes the scope to ONE pair: the delayed-entry test settles the single
# non-negative index result (D-015). No other pair is run under this driver.
PAIR = ("MES", "M2K")

# D-022 / L-019: which HALF of the battery this run emits. Both parts compute
# everything; only the emission dict differs. 1 = Z0 half, 2 = Z2 half +
# cross-correlation. Set to 2 for the second backtest; nothing else changes.
PART = 1

ANCHOR = "vol_ratio" if PAIR[0] in TREASURIES else "unit"

# L-009: MYM data exists ONLY under CBOT. The other index micros are CME; all
# treasuries are CBOT. Wrong market here means a silent resolve failure.
MARKETS = {"MES": Market.CME, "MNQ": Market.CME,
           "M2K": Market.CME, "MYM": Market.CBOT,
           "ZT": Market.CBOT, "ZF": Market.CBOT,
           "ZN": Market.CBOT, "ZB": Market.CBOT}
LEGS = {sym: MARKETS[sym] for sym in PAIR}

WINDOW_START = datetime(2019, 6, 1)              # micros launched 2019-05-06
WINDOW_END = datetime(2026, 4, 27)               # inside the free-tier clip
GATE_WINDOW_BARS = 390

# Adjudication of a flagged splice (D-010 + amendment A1): a flag is a real
# artifact only if the calendar gap can EXPLAIN it — material, same-signed,
# and inside a band around the splice return. Both bounds.
GAPSHAPED_LO = 0.6
GAPSHAPED_HI = 1.6


class PairMinuteAnalysis(QCAlgorithm):

    def initialize(self):
        self.set_start_date(2026, 4, 28)     # History-only pattern, inside clip
        self.set_end_date(2026, 4, 29)
        self.set_cash(100_000)
        self.set_benchmark(lambda dt: 0)
        self.results = {}
        try:
            self._run()
        except Exception as e:
            import traceback
            self.results["S_FATAL"] = str(e)[:110]
            self.results["S_FATAL_TB"] = traceback.format_exc()[-240:]

    # -- build + gate -------------------------------------------------------

    def _run(self):
        hol = cme_holidays()
        self.results["S_HOLIDAYS"] = (
            f"n={len(hol)}|memorial21={int(date(2021, 5, 31) in hol)}|"
            f"span={min(hol).year}-{max(hol).year}")

        built = {}
        for leg, market in LEGS.items():
            built[leg] = self._build(leg, market, hol)
            if built[leg][0] is None:
                return

        if not all(self._emit_gate(leg, *built[leg][1:]) for leg in LEGS):
            self.results["S_GATE"] = "FAIL|analysis suppressed per D-010"
            return
        self.results["S_GATE"] = "PASS|both legs adjudicated non-gap-shaped"

        a, b = PAIR
        self.results["S_PAIR"] = (
            f"{a}_{b}|markets={LEGS[a]}/{LEGS[b]}|anchor={ANCHOR}|"
            f"rolls={'treasury' if a in TREASURIES else 'index'}|nb=14|"
            f"part={PART}")
        # No roll timestamps or splice factors are passed: as in notebook 06,
        # this battery has no preflight block. Roll effects are common-mode
        # across delays (the same events are read at different entry bars).
        self.results.update(pair_delayed_entry_report(
            built[a][0], built[b][0], anchor=ANCHOR, part=PART))

    def _build(self, leg, market, hol):
        is_tsy = leg in TREASURIES
        codes = [leg + c for c in (CODES_TREASURY if is_tsy else CODES_INDEX)]
        fut = self.add_future(
            leg, Resolution.MINUTE, market=market, fill_forward=False,
            extended_market_hours=True,
            data_mapping_mode=DataMappingMode.OPEN_INTEREST,
            data_normalization_mode=DataNormalizationMode.BACKWARDS_RATIO,
            contract_depth_offset=0)
        fut.set_filter(0, 0)

        if is_tsy:
            sched = treasury_roll_schedule(codes, splice_time=time(10, 30),
                                           tz=None, holidays=hol)
        else:
            sched = index_roll_schedule(codes, days_before=8,
                                        splice_time=time(10, 30), tz=None,
                                        holidays=hol)
        times = list(pd.to_datetime(sched["timestamp"]))
        starts, ends = [WINDOW_START] + times, times + [WINDOW_END]

        segments = {}
        for i, code in enumerate(codes):
            sym = self._resolve(fut.symbol, code)
            if sym is None:
                self.results["S_RESOLVE_FAIL"] = f"{leg}|{code}"
                return None, None, None, None
            h = self.history(sym, starts[i] - timedelta(days=6),
                             ends[i] + timedelta(days=1), Resolution.MINUTE)
            if h is None or h.empty or "close" not in h.columns:
                self.results["S_DATA_FAIL"] = f"{leg}|{code}"
                return None, None, None, None
            h = h.reset_index()
            tcol = "time" if "time" in h.columns else h.columns[1]
            s = pd.Series(h["close"].astype(float).values,
                          index=pd.DatetimeIndex(h[tcol])).sort_index()
            segments[code] = pd.DataFrame({"close": s[~s.index.duplicated("first")]})

        cont, table = build_continuous(segments, sched, price_cols=("close",))
        del segments
        audit = splice_audit(cont["close"], sched, window_bars=GATE_WINDOW_BARS)
        close = cont["close"]
        # Drop the first segment's pre-window fetch buffer (driver note,
        # validation report 01 section 6).
        close = close[(close.index >= WINDOW_START) & (close.index <= WINDOW_END)]
        return close, sched, table, audit

    def _emit_gate(self, leg, sched, table, audit):
        merged = table.merge(audit, on="timestamp")
        flagged = merged[merged["artifact_flag"]]
        self.results["S_BUILD_" + leg] = (
            f"rolls={len(merged)}|flags={len(flagged)}|"
            f"med_ovl={int(merged['n_overlap'].median())}|"
            f"nonmedian={int((merged['method'] != 'median_ratio').sum())}")
        # The S_RL per-roll block is deliberately NOT emitted (D-022 / L-019):
        # it is the block the channel silently dropped in every nb06 run, its
        # content cannot change with the entry bar, and dropping it keeps each
        # part inside the 57-key envelope the channel has actually delivered.

        gapshaped = []
        for _, r in flagged.iterrows():
            sr_s, gp_s = float(r["splice_ret_pct"]), float(r["factor_gap_pct"])
            sr, gp = abs(sr_s), abs(gp_s)
            thr = float(r["threshold"]) * 100.0
            material = gp > thr
            same_sign = (sr_s * gp_s) > 0
            in_band = GAPSHAPED_LO * gp <= sr <= GAPSHAPED_HI * gp
            bad = bool(material and same_sign and in_band)
            gapshaped.append(bad)
            why = ("gap_explains_it" if bad else
                   "gap_immaterial" if not material else
                   "sign_mismatch" if not same_sign else
                   "sr_below_gap" if sr < GAPSHAPED_LO * gp else "sr_exceeds_gap")
            self.results["S_FLAG_" + leg + pd.Timestamp(
                r["timestamp"]).strftime("%y%m%d")] = (
                f"sr={fmt(sr_s)}|gap={fmt(gp_s)}|thr={fmt(thr)}|"
                f"mad={fmt(r['local_mad'] * 100, 5)}|ratio={fmt(sr / gp if gp else float('nan'), 2)}|"
                f"gapshaped={int(bad)}|why={why}")
        return not any(gapshaped)

    def _resolve(self, canonical, code):
        root, month, year = parse_contract(code)
        anchor = (last_business_day_of_month(year, month) if root in TREASURIES
                  else third_friday(year, month))
        for back in (25, 55, 85, 5):
            probe = datetime(anchor.year, anchor.month, anchor.day) - \
                timedelta(days=back)
            try:
                for s in self.future_chain_provider.get_future_contract_list(
                        canonical, probe):
                    if s.id.date.year == year and s.id.date.month == month:
                        return s
            except Exception:
                continue
        return None

    def on_data(self, slice):
        pass

    def on_end_of_algorithm(self):
        self.results["S_KEYS"] = str(len(self.results) + 1)
        for k, v in self.results.items():
            self.set_summary_statistic(k, str(v)[:960])
