"""Notebooks 02/03 — minute-level PAIR analysis on OWN-SPLICE series.

NOT the trading algorithm (CLAUDE.md gate 1). Zero orders; the only
subscription exists so `future_chain_provider` can resolve contract symbols.

This driver is deliberately thin. Every statistic lives in
`src/spread_research/` and is unit-tested locally against known answers
(`tests/unit/test_pair_minute_report.py`), because a QC backtest is a slow and
expensive place to discover a typo. The driver's own job is only:

  1. Build OUR roll schedule per leg (index rule, expiry-8d, 10:30 ET) with the
     CME holiday list from `calendars.cme_holidays()`.
  2. Fetch per-contract minute closes and `build_continuous()` each leg.
  3. `splice_audit()` each constructed series — the D-010 ACCEPTANCE GATE.
     If a leg fails and its flags are not adjudicable from the emitted numbers,
     NO analysis is produced. The gate lives inside this run, not in a separate
     one, so analysis can never quietly consume an unvetted series.
  4. Hand the two gated series to `pair_minute_report()`.

Output channel: `set_summary_statistic` in `on_end_of_algorithm` — the free
tier caps logs at 10KB/backtest AND 10KB/day, so summary statistics are the
only reliable bulk channel. Values are pipe-delimited; see
`scripts/ingest_qc_pair_minute.py` for the parser.

Uploaded alongside as flat QC project files: roll_adjustment.py, calendars.py,
intraday_reversion.py, signals.py, pair_minute_report.py (generated by
`scripts/build_qc_upload.py`, which only rewrites relative imports).
"""

from AlgorithmImports import *
from datetime import date, datetime, time, timedelta

import pandas as pd

from calendars import cme_holidays
from pair_minute_report import fmt, pair_minute_report
from roll_adjustment import (
    build_continuous, index_roll_schedule, last_business_day_of_month,
    parse_contract, splice_audit, third_friday, treasury_roll_schedule,
)

# Quarterly chains over the research window. Index micros roll 8 days before a
# 3rd-Friday expiry, so the June-2019 contract is still front on 2019-06-01 and
# the chain opens at M19. Treasuries roll on the last business day of the month
# BEFORE the delivery month, so ZxM19 has already rolled off by 2019-06-01 and
# the chain opens at U19 — 28 codes / 27 rolls, matching the EXP-007 ZN
# acceptance run exactly.
CODES_INDEX = ["M19", "U19", "Z19", "H20", "M20", "U20", "Z20", "H21", "M21",
               "U21", "Z21", "H22", "M22", "U22", "Z22", "H23", "M23", "U23",
               "Z23", "H24", "M24", "U24", "Z24", "H25", "M25", "U25", "Z25",
               "H26", "M26"]
CODES_TREASURY = CODES_INDEX[1:]

TREASURIES = ("ZT", "ZF", "ZN", "ZB")

# Set PAIR to run a different pair; nothing else in this file needs editing.
# Order matters: PAIR[0] is leg A (the numerator/left leg of the S1 residual).
PAIR = ("ZF", "ZN")

# S1's anchor is an ECONOMIC choice, not a knob (see residual_specs):
#   index micros  -> "unit"      (both legs comparable duration; beta = 1)
#   treasuries    -> "vol_ratio" (ZT has ~1/5 of ZN's duration; D-008 mandates
#                                 an ADAPTIVE hedge for the curve)
ANCHOR = "vol_ratio" if PAIR[0] in TREASURIES else "unit"

# L-009: MYM data exists ONLY under CBOT (CME serves zero bars for it). The
# other index micros are CME; all treasuries are CBOT. Wrong market here means
# a silent resolve failure, so the mapping is explicit rather than defaulted.
MARKETS = {"MES": Market.CME, "MNQ": Market.CME,
           "M2K": Market.CME, "MYM": Market.CBOT,
           "ZT": Market.CBOT, "ZF": Market.CBOT,
           "ZN": Market.CBOT, "ZB": Market.CBOT}
LEGS = {sym: MARKETS[sym] for sym in PAIR}

WINDOW_START = datetime(2019, 6, 1)              # micros launched 2019-05-06
WINDOW_END = datetime(2026, 4, 27)               # inside the free-tier clip
GATE_WINDOW_BARS = 390

# Adjudication of a flagged splice (D-010 + amendment A1).
#
# A splice-audit flag only says "this boundary return is large relative to the
# local MAD". That has two possible causes: a bad splice factor, or a genuine
# market move at that minute. The discriminator is a BOUND: the error a wrong
# factor can inject is at most the calendar gap that factor was removing. So a
# flag is a real artifact only if the gap can actually explain it —
#
#   * the gap must itself be material (bigger than the audit threshold; a gap
#     buried in the local noise cannot produce a flag), AND
#   * the splice return must have the same sign as the gap, AND
#   * its magnitude must sit inside a band around the gap: too small and the
#     factor clearly worked, too large and the gap is arithmetically incapable
#     of being the cause.
#
# The original one-sided rule (|sr| >= 0.6*|gap|) was satisfied by ANY small
# gap and mislabelled a quiet-market news move as a defect — see amendment A1
# in logs/research_decisions.md.
GAPSHAPED_LO = 0.6
GAPSHAPED_HI = 1.6


class PairMinuteAnalysis(QCAlgorithm):

    def initialize(self):
        self.set_start_date(2026, 4, 28)     # History-only pattern, inside clip
        self.set_end_date(2026, 4, 29)
        self.set_cash(100_000)
        self.set_benchmark(lambda dt: 0)
        self.results = {}
        try:
            self._run()
        except Exception as e:
            import traceback
            self.results["S_FATAL"] = str(e)[:110]
            self.results["S_FATAL_TB"] = traceback.format_exc()[-240:]

    # -- build + gate -------------------------------------------------------

    def _run(self):
        hol = cme_holidays()
        self.results["S_HOLIDAYS"] = (
            f"n={len(hol)}|memorial21={int(date(2021, 5, 31) in hol)}|"
            f"span={min(hol).year}-{max(hol).year}")

        built = {}
        for leg, market in LEGS.items():
            built[leg] = self._build(leg, market, hol)
            if built[leg][0] is None:
                return

        if not all(self._emit_gate(leg, *built[leg][1:]) for leg in LEGS):
            self.results["S_GATE"] = "FAIL|analysis suppressed per D-010"
            return
        self.results["S_GATE"] = "PASS|both legs adjudicated non-gap-shaped"

        a, b = PAIR
        sched_a, table_a = built[a][1], built[a][2]
        self.results["S_PAIR"] = (
            f"{a}_{b}|markets={LEGS[a]}/{LEGS[b]}|anchor={ANCHOR}|"
            f"rolls={'treasury' if a in TREASURIES else 'index'}")
        self.results.update(pair_minute_report(
            built[a][0], built[b][0],
            roll_timestamps=list(pd.to_datetime(sched_a["timestamp"])),
            factors_a=table_a.set_index("timestamp")["factor"],
            factors_b=built[b][2].set_index("timestamp")["factor"],
            anchor=ANCHOR))

    def _build(self, leg, market, hol):
        is_tsy = leg in TREASURIES
        codes = [leg + c for c in (CODES_TREASURY if is_tsy else CODES_INDEX)]
        fut = self.add_future(
            leg, Resolution.MINUTE, market=market, fill_forward=False,
            extended_market_hours=True,
            data_mapping_mode=DataMappingMode.OPEN_INTEREST,
            data_normalization_mode=DataNormalizationMode.BACKWARDS_RATIO,
            contract_depth_offset=0)
        fut.set_filter(0, 0)

        if is_tsy:
            # Month-end before the delivery month. Report 01 section 2 showed QC
            # flips treasuries 18-36 days pre-expiry at only 15-52% volume
            # share, so its flip is the wrong event here just as it is for the
            # index micros.
            sched = treasury_roll_schedule(codes, splice_time=time(10, 30),
                                           tz=None, holidays=hol)
        else:
            sched = index_roll_schedule(codes, days_before=8,
                                        splice_time=time(10, 30), tz=None,
                                        holidays=hol)
        times = list(pd.to_datetime(sched["timestamp"]))
        starts, ends = [WINDOW_START] + times, times + [WINDOW_END]

        segments = {}
        for i, code in enumerate(codes):
            sym = self._resolve(fut.symbol, code)
            if sym is None:
                self.results["S_RESOLVE_FAIL"] = f"{leg}|{code}"
                return None, None, None, None
            h = self.history(sym, starts[i] - timedelta(days=6),
                             ends[i] + timedelta(days=1), Resolution.MINUTE)
            if h is None or h.empty or "close" not in h.columns:
                self.results["S_DATA_FAIL"] = f"{leg}|{code}"
                return None, None, None, None
            h = h.reset_index()
            tcol = "time" if "time" in h.columns else h.columns[1]
            s = pd.Series(h["close"].astype(float).values,
                          index=pd.DatetimeIndex(h[tcol])).sort_index()
            segments[code] = pd.DataFrame({"close": s[~s.index.duplicated("first")]})

        cont, table = build_continuous(segments, sched, price_cols=("close",))
        del segments
        audit = splice_audit(cont["close"], sched, window_bars=GATE_WINDOW_BARS)
        close = cont["close"]
        # Drop the first segment's pre-window fetch buffer (driver note,
        # validation report 01 section 6).
        close = close[(close.index >= WINDOW_START) & (close.index <= WINDOW_END)]
        return close, sched, table, audit

    def _emit_gate(self, leg, sched, table, audit):
        merged = table.merge(audit, on="timestamp")
        flagged = merged[merged["artifact_flag"]]
        self.results["S_BUILD_" + leg] = (
            f"rolls={len(merged)}|flags={len(flagged)}|"
            f"med_ovl={int(merged['n_overlap'].median())}|"
            f"nonmedian={int((merged['method'] != 'median_ratio').sum())}")
        recs = [f"{pd.Timestamp(r['timestamp']).strftime('%y%m%d')},"
                f"{fmt(r['splice_ret_pct'], 3)},{fmt(r['factor_gap_pct'], 3)},"
                f"{int(r['artifact_flag'])}" for _, r in merged.iterrows()]
        for i in range(0, len(recs), 5):
            self.results[f"S_RL{leg}{i // 5:02d}"] = "|".join(recs[i:i + 5])

        gapshaped = []
        for _, r in flagged.iterrows():
            sr_s, gp_s = float(r["splice_ret_pct"]), float(r["factor_gap_pct"])
            sr, gp = abs(sr_s), abs(gp_s)
            thr = float(r["threshold"]) * 100.0
            material = gp > thr
            same_sign = (sr_s * gp_s) > 0
            in_band = GAPSHAPED_LO * gp <= sr <= GAPSHAPED_HI * gp
            bad = bool(material and same_sign and in_band)
            gapshaped.append(bad)
            why = ("gap_explains_it" if bad else
                   "gap_immaterial" if not material else
                   "sign_mismatch" if not same_sign else
                   "sr_below_gap" if sr < GAPSHAPED_LO * gp else "sr_exceeds_gap")
            self.results["S_FLAG_" + leg + pd.Timestamp(
                r["timestamp"]).strftime("%y%m%d")] = (
                f"sr={fmt(sr_s)}|gap={fmt(gp_s)}|thr={fmt(thr)}|"
                f"mad={fmt(r['local_mad'] * 100, 5)}|ratio={fmt(sr / gp if gp else float('nan'), 2)}|"
                f"gapshaped={int(bad)}|why={why}")
        return not any(gapshaped)

    def _resolve(self, canonical, code):
        root, month, year = parse_contract(code)
        anchor = (last_business_day_of_month(year, month) if root in TREASURIES
                  else third_friday(year, month))
        for back in (25, 55, 85, 5):
            probe = datetime(anchor.year, anchor.month, anchor.day) - \
                timedelta(days=back)
            try:
                for s in self.future_chain_provider.get_future_contract_list(
                        canonical, probe):
                    if s.id.date.year == year and s.id.date.month == month:
                        return s
            except Exception:
                continue
        return None

    def on_data(self, slice):
        pass

    def on_end_of_algorithm(self):
        self.results["S_KEYS"] = str(len(self.results) + 1)
        for k, v in self.results.items():
            self.set_summary_statistic(k, str(v)[:960])
