"""Notebook 15 — SESSION WINDOW on OWN-SPLICE series (A-013, L-021; D-024).

NOT the trading algorithm (CLAUDE.md gate 1). Zero orders; the only
subscription exists so `future_chain_provider` can resolve contract symbols.

Identical to `qc_pair_minute_analysis.py` in every respect that D-009 and the
D-010 acceptance gate depend on: the same roll schedule, the same
`build_continuous`, the same `splice_audit` with the same A1 adjudication
bound. Only the final call differs — `session_window_report()` — because D-024
changes WHICH BARS form the panel and nothing else.

**L-021, the reason this run exists.** `rth_frame` filters on the clock the
DATA carries. LEAN stamps CBOT Treasury bars in America/Chicago and index bars
in America/New_York, so the four Treasury pairs were analysed on
09:30-16:00 CT = **10:31-17:00 ET**, not the 09:30-16:00 ET every document
claims — missing the morning and running two hours past the 15:00 ET Treasury
settlement. Every window constant below is therefore in the DATA's own stamps,
and `S_TZWIT` emits the delivered span so the assumption is CHECKED. Bar count
is not a witness: any 390-minute window inside a 23h session gives 390 bars,
which is exactly how this hid for seven runs.

PART (L-019 + D-024 §5): the battery ships as THREE backtests, split by
window so no part exceeds the ~57-key ceiling.
    PART 1 -> S-USED + S-HALF   (regular-session fetch, banked data path)
    PART 2 -> S-RTH  + S-SETTLE (regular-session fetch, banked data path)
    PART 3 -> S-CASH            (EXTENDED-hours fetch — see below)
Parts 1 and 2 leave the data path byte-identical to the banked runs, so
`S_GATE` / `S_BUILD_*` / `S_FLAG_*` / `S_FACTAB` must come back exactly as
banked — a 6th determinism demonstration of D-009.

PART 3 and the S-CASH-ENABLE gate (D-024 §3). S-CASH needs bars before
08:30 CT, which `self.history(contract, ...)` does not return (it delivers the
LEAN regular session only, ~450 bars/day). Requesting extended hours would
change `build_continuous`'s 390-bar factor window from ~0.87 of a day to
~0.28-0.35, producing different factors and breaking comparability with every
banked result. The frozen requirement is therefore: **measure the factors and
run `splice_audit` on the identical bar set the banked runs used, then
re-apply those factors to the denser analysis series** via
`build_continuous(..., factors=...)`. `S_FACTAB` — the full factor table, not
a digest — is the witness: if it does not reproduce parts 1-2 exactly, the
S-CASH arm is VOID and unreported.

PART 3 satisfies that with TWO fetches rather than by subsetting one, and the
reason is scientific. `history()` on a CONTRACT symbol does not inherit the
canonical subscription's config — the banked runs prove it, since
`add_future(..., fill_forward=False, extended_market_hours=True)` still yields
a delivered span of 08:31-16:00 — so LEAN's defaults apply, including
fill_forward=TRUE. A single extended fetch would hand S-CASH a 07:21-08:30
block of forward-filled repeats: the coverage finding would be meaningless and
the grid and variance ratios would be computed on stale prices. So the factors
keep the byte-identical banked regular call, and only the ANALYSIS series is
refetched extended with fill-forward OFF. `S_FILLWIT` records which regime
produced which series so a reader never has to infer it.

Output channel: `set_summary_statistic` in `on_end_of_algorithm` — the free
tier caps logs at 10KB/backtest AND 10KB/day. See
`scripts/ingest_qc_session_window.py` for the parser and the D-024 gates.

Uploaded alongside as flat QC project files: calendars.py, signals.py,
roll_adjustment.py, intraday_reversion.py, crosscorr.py, pair_minute_report.py,
session_window_report.py (generated by
`python scripts/build_qc_upload.py --driver session`).
"""

from AlgorithmImports import *
from datetime import date, datetime, time, timedelta

import pandas as pd

from calendars import cme_holidays
from pair_minute_report import fmt
from roll_adjustment import (
    build_continuous, last_business_day_of_month, parse_contract, splice_audit,
    treasury_roll_schedule,
)
from session_window_report import session_window_report

# Quarterly chain. Treasuries roll on the last business day of the month BEFORE
# the delivery month, so ZxM19 has already rolled off by 2019-06-01 and the
# chain opens at U19 — 28 codes / 27 rolls, matching EXP-007 exactly.
CODES_TREASURY = ["U19", "Z19", "H20", "M20", "U20", "Z20", "H21", "M21",
                  "U21", "Z21", "H22", "M22", "U22", "Z22", "H23", "M23",
                  "U23", "Z23", "H24", "M24", "U24", "Z24", "H25", "M25",
                  "U25", "Z25", "H26", "M26"]

# D-024 §4 fixes the scope to the four Treasury pairs and their order
# (liquidity-first, registered together so the protocol cannot be adjusted
# between them): ZF-ZN -> ZT-ZF -> ZN-ZB -> ZT-ZN. No index pair is run.
PAIR = ("ZF", "ZN")

# D-024 §5: which third of the battery this backtest emits. Set to 1, 2, then
# 3; nothing else in this file needs editing.
PART = 1

ANCHOR = "vol_ratio"          # D-008: the curve needs an adaptive hedge

MARKETS = {"ZT": Market.CBOT, "ZF": Market.CBOT,
           "ZN": Market.CBOT, "ZB": Market.CBOT}
LEGS = {sym: MARKETS[sym] for sym in PAIR}

WINDOW_START = datetime(2019, 6, 1)
WINDOW_END = datetime(2026, 4, 27)
GATE_WINDOW_BARS = 390

# A1 adjudication of a flagged splice: a flag is a real artifact only if the
# calendar gap can EXPLAIN it — material, same-signed, and inside a band around
# the splice return. Both bounds.
GAPSHAPED_LO = 0.6
GAPSHAPED_HI = 1.6


class PairMinuteAnalysis(QCAlgorithm):

    def initialize(self):
        self.set_start_date(2026, 4, 28)     # History-only pattern, inside clip
        self.set_end_date(2026, 4, 29)
        self.set_cash(100_000)
        self.set_benchmark(lambda dt: 0)
        self.results = {}
        try:
            self._run()
        except Exception as e:
            import traceback
            self.results["S_FATAL"] = str(e)[:110]
            self.results["S_FATAL_TB"] = traceback.format_exc()[-240:]

    # -- build + gate -------------------------------------------------------

    def _run(self):
        hol = cme_holidays()
        self.results["S_HOLIDAYS"] = (
            f"n={len(hol)}|memorial21={int(date(2021, 5, 31) in hol)}|"
            f"span={min(hol).year}-{max(hol).year}")

        built = {}
        for leg, market in LEGS.items():
            built[leg] = self._build(leg, market, hol)
            if built[leg][0] is None:
                return

        if not all(self._emit_gate(leg, *built[leg][1:]) for leg in LEGS):
            self.results["S_GATE"] = "FAIL|analysis suppressed per D-010"
            return
        self.results["S_GATE"] = "PASS|both legs adjudicated non-gap-shaped"

        a, b = PAIR
        self.results["S_PAIR"] = (
            f"{a}_{b}|markets={LEGS[a]}/{LEGS[b]}|anchor={ANCHOR}|"
            f"rolls=treasury|nb=15|part={PART}|"
            f"fetch={'extended' if PART == 3 else 'regular'}")
        # No roll timestamps or splice factors are passed: as in notebooks 06
        # and 14 this battery has no preflight block. Roll windows were adopted
        # in report 02 §6.3 and re-measuring them cannot change with a session.
        self.results.update(session_window_report(
            built[a][0], built[b][0], part=PART, anchor=ANCHOR,
            legs_names=PAIR))

    def _build(self, leg, market, hol):
        codes = [leg + c for c in CODES_TREASURY]
        fut = self.add_future(
            leg, Resolution.MINUTE, market=market, fill_forward=False,
            extended_market_hours=True,
            data_mapping_mode=DataMappingMode.OPEN_INTEREST,
            data_normalization_mode=DataNormalizationMode.BACKWARDS_RATIO,
            contract_depth_offset=0)
        fut.set_filter(0, 0)

        # Month-end before the delivery month. Report 01 §2 measured QC's own
        # OpenInterest flip at 18-36 days pre-expiry with only 15-52% volume
        # share, i.e. the wrong event.
        sched = treasury_roll_schedule(codes, splice_time=time(10, 30),
                                       tz=None, holidays=hol)
        times = list(pd.to_datetime(sched["timestamp"]))
        starts, ends = [WINDOW_START] + times, times + [WINDOW_END]

        segments, reg_seg = {}, {}
        for i, code in enumerate(codes):
            sym = self._resolve(fut.symbol, code)
            if sym is None:
                self.results["S_RESOLVE_FAIL"] = f"{leg}|{code}"
                return None, None, None, None
            lo, hi = starts[i] - timedelta(days=6), ends[i] + timedelta(days=1)
            # PART 3 issues TWO fetches, and the reason is scientific rather
            # than cosmetic. `history()` on a CONTRACT symbol does not inherit
            # the canonical subscription's config (the banked runs prove it:
            # `add_future(extended_market_hours=True)` yet the delivered span
            # is the regular 08:31-16:00), so LEAN's defaults apply — including
            # fill_forward=TRUE. A single extended fetch would therefore hand
            # S-CASH a 07:21-08:30 block of synthetic repeats: the coverage
            # finding would be meaningless and the grid would be computed on
            # stale prices. So the factors keep the byte-identical banked
            # regular call, and only the ANALYSIS series is refetched extended
            # with fill-forward OFF. D-024 §3's requirement — factors measured
            # on the identical bar set the banked runs used — is satisfied more
            # strictly this way than by subsetting one filled fetch.
            h = self.history(sym, lo, hi, Resolution.MINUTE)
            if h is None or h.empty or "close" not in h.columns:
                self.results["S_DATA_FAIL"] = f"{leg}|{code}"
                return None, None, None, None
            reg_seg[code] = self._frame(h)
            if PART == 3:
                he = self.history(sym, lo, hi, Resolution.MINUTE,
                                  fill_forward=False,
                                  extended_market_hours=True)
                if he is None or he.empty or "close" not in he.columns:
                    self.results["S_DATA_FAIL"] = f"{leg}|{code}|extended"
                    return None, None, None, None
                segments[code] = self._frame(he)
            else:
                segments[code] = reg_seg[code]

        # D-024 §3: factors and the acceptance gate are ALWAYS measured on the
        # regular-session bar set — byte-identical to the banked runs — and only
        # then re-applied to the (possibly denser) analysis series. This is what
        # keeps the D-009 construction unchanged under PART 3.
        cont_reg, table = build_continuous(reg_seg, sched, price_cols=("close",))
        audit = splice_audit(cont_reg["close"], sched, window_bars=GATE_WINDOW_BARS)

        facs = {(r["from_contract"], r["to_contract"]): float(r["factor"])
                for _, r in table.iterrows()}
        # The FULL factor table, not a digest: D-024 §3 requires the S-CASH
        # arm to reproduce it "character for character", and n/min/max/product
        # can collide. 27 factors at 6 dp is ~250 chars, well inside the cap.
        self.results["S_FACTAB_" + leg] = ",".join(
            fmt(facs[k], 6) for k in sorted(facs))
        self.results["S_FILLWIT_" + leg] = (
            f"analysis_fetch={'extended_ff_off' if PART == 3 else 'regular_default'}"
            f"|factor_fetch=regular_default|n_fac={len(facs)}")

        if PART == 3:
            cont, _ = build_continuous(segments, sched, price_cols=("close",),
                                       factors=facs)
        else:
            cont = cont_reg
        del segments, reg_seg, cont_reg
        close = cont["close"]
        # Drop the first segment's pre-window fetch buffer (validation report
        # 01 §6).
        close = close[(close.index >= WINDOW_START) & (close.index <= WINDOW_END)]
        return close, sched, table, audit

    def _emit_gate(self, leg, sched, table, audit):
        merged = table.merge(audit, on="timestamp")
        flagged = merged[merged["artifact_flag"]]
        self.results["S_BUILD_" + leg] = (
            f"rolls={len(merged)}|flags={len(flagged)}|"
            f"med_ovl={int(merged['n_overlap'].median())}|"
            f"nonmedian={int((merged['method'] != 'median_ratio').sum())}")
        # The S_RL per-roll block is deliberately NOT emitted (D-022/L-019):
        # it is the block the channel silently dropped in every nb06 run, and
        # dropping it keeps each part inside the 57-key envelope.

        gapshaped = []
        for _, r in flagged.iterrows():
            sr_s, gp_s = float(r["splice_ret_pct"]), float(r["factor_gap_pct"])
            sr, gp = abs(sr_s), abs(gp_s)
            thr = float(r["threshold"]) * 100.0
            material = gp > thr
            same_sign = (sr_s * gp_s) > 0
            in_band = GAPSHAPED_LO * gp <= sr <= GAPSHAPED_HI * gp
            bad = bool(material and same_sign and in_band)
            gapshaped.append(bad)
            why = ("gap_explains_it" if bad else
                   "gap_immaterial" if not material else
                   "sign_mismatch" if not same_sign else
                   "sr_below_gap" if sr < GAPSHAPED_LO * gp else "sr_exceeds_gap")
            self.results["S_FLAG_" + leg + pd.Timestamp(
                r["timestamp"]).strftime("%y%m%d")] = (
                f"sr={fmt(sr_s)}|gap={fmt(gp_s)}|thr={fmt(thr)}|"
                f"mad={fmt(r['local_mad'] * 100, 5)}|"
                f"ratio={fmt(sr / gp if gp else float('nan'), 2)}|"
                f"gapshaped={int(bad)}|why={why}")
        return not any(gapshaped)

    @staticmethod
    def _frame(h):
        h = h.reset_index()
        tcol = "time" if "time" in h.columns else h.columns[1]
        s = pd.Series(h["close"].astype(float).values,
                      index=pd.DatetimeIndex(h[tcol])).sort_index()
        return pd.DataFrame({"close": s[~s.index.duplicated("first")]})

    def _resolve(self, canonical, code):
        root, month, year = parse_contract(code)
        anchor = last_business_day_of_month(year, month)
        for back in (25, 55, 85, 5):
            probe = datetime(anchor.year, anchor.month, anchor.day) - \
                timedelta(days=back)
            try:
                for s in self.future_chain_provider.get_future_contract_list(
                        canonical, probe):
                    if s.id.date.year == year and s.id.date.month == month:
                        return s
            except Exception:
                continue
        return None

    def on_data(self, slice):
        pass

    def on_end_of_algorithm(self):
        self.results["S_KEYS"] = str(len(self.results) + 1)
        for k, v in self.results.items():
            self.set_summary_statistic(k, str(v)[:960])
